//! Units and unit-aware value editors. Everything in the simulation is SI; conversion for
//! display and input happens here and nowhere else.

use bevy_egui::egui;
use cosmogon_sim::astro::{Quality, AU, EARTH_MASS, EARTH_RADIUS, JUPITER_MASS, JUPITER_RADIUS, SOLAR_MASS, SOLAR_RADIUS};

use super::{MUTED, TEXT};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Quantity {
    Mass,
    Length,
    Speed,
    Temperature,
    Duration,
    Angle,
    Pressure,
    Fraction,
    Plain,
}

pub struct Unit {
    pub label: &'static str,
    /// SI = value × factor + offset.
    pub factor: f64,
    pub offset: f64,
}

const fn u(label: &'static str, factor: f64) -> Unit {
    Unit { label, factor, offset: 0.0 }
}

pub const MASS: &[Unit] = &[u("kg", 1.0), u("Earth masses", EARTH_MASS), u("Jupiter masses", JUPITER_MASS), u("Solar masses", SOLAR_MASS)];
pub const LENGTH: &[Unit] = &[u("m", 1.0), u("km", 1000.0), u("Earth radii", EARTH_RADIUS), u("Jupiter radii", JUPITER_RADIUS), u("Solar radii", SOLAR_RADIUS), u("AU", AU)];
pub const SPEED: &[Unit] = &[u("m/s", 1.0), u("km/s", 1000.0)];
pub const TEMPERATURE: &[Unit] = &[Unit { label: "K", factor: 1.0, offset: 0.0 }, Unit { label: "°C", factor: 1.0, offset: 273.15 }];
pub const DURATION: &[Unit] = &[u("s", 1.0), u("hours", 3600.0), u("days", 86_400.0), u("years", 365.25 * 86_400.0)];
pub const ANGLE: &[Unit] = &[u("°", std::f64::consts::PI / 180.0)];
pub const PRESSURE: &[Unit] = &[u("bar", 1.0)];
pub const FRACTION: &[Unit] = &[u("%", 0.01)];
pub const PLAIN: &[Unit] = &[u("", 1.0)];

pub fn units(q: Quantity) -> &'static [Unit] {
    match q {
        Quantity::Mass => MASS,
        Quantity::Length => LENGTH,
        Quantity::Speed => SPEED,
        Quantity::Temperature => TEMPERATURE,
        Quantity::Duration => DURATION,
        Quantity::Angle => ANGLE,
        Quantity::Pressure => PRESSURE,
        Quantity::Fraction => FRACTION,
        Quantity::Plain => PLAIN,
    }
}

/// Plain number formatting with scientific notation for very large/small magnitudes.
pub fn fmt_num(v: f64) -> String {
    let a = v.abs();
    if v == 0.0 {
        "0".into()
    } else if !(1e-3..1e7).contains(&a) {
        format!("{v:.5e}")
    } else if a >= 1000.0 {
        format!("{v:.1}")
    } else if a >= 1.0 {
        format!("{v:.4}")
    } else {
        format!("{v:.6}")
    }
}

pub fn quality_badge(ui: &mut egui::Ui, q: Quality) {
    let color = match q {
        Quality::Measured => egui::Color32::from_rgb(110, 180, 240),
        Quality::Derived => egui::Color32::from_rgb(150, 160, 190),
        Quality::Estimated => egui::Color32::from_rgb(220, 180, 90),
        Quality::Procedural => egui::Color32::from_rgb(170, 130, 220),
        Quality::UserModified => egui::Color32::from_rgb(235, 140, 90),
    };
    let tip = match q {
        Quality::Measured => "From an observational dataset (see DATA tab for the source).",
        Quality::Derived => "Computed from other values by a documented model.",
        Quality::Estimated => "Model estimate: no direct measurement exists.",
        Quality::Procedural => "Generated by Cosmogon from a seed — not observed.",
        Quality::UserModified => "Changed by you in this sandbox.",
    };
    ui.label(egui::RichText::new(q.label()).size(9.0).color(color).strong()).on_hover_text(tip);
}

/// An editable physical quantity: drag or type (scientific notation accepted) in any unit.
/// The edit is committed when dragging stops or Enter / focus loss ends typing, so one
/// gesture is one undo step. Returns the new SI value.
pub fn edit(ui: &mut egui::Ui, salt: impl std::hash::Hash, si: f64, q: Quantity, default_unit: usize, editable: bool, quality: Option<Quality>) -> Option<f64> {
    let id = ui.id().with(("qty", salt));
    let us = units(q);
    let mut unit = ui.memory(|m| m.data.get_temp::<usize>(id.with("unit"))).unwrap_or(default_unit).min(us.len() - 1);
    let mut out = None;
    ui.horizontal(|ui| {
        let u = &us[unit];
        let to_unit = |v: f64| (v - u.offset) / u.factor;
        let editing: bool = ui.memory(|m| m.data.get_temp(id.with("editing"))).unwrap_or(false);
        let mut shown: f64 = if editing { ui.memory(|m| m.data.get_temp(id.with("value"))).unwrap_or(to_unit(si)) } else { to_unit(si) };
        if editable {
            let speed = (shown.abs() * 0.004).max(1e-9);
            let r = ui.add(
                egui::DragValue::new(&mut shown)
                    .speed(speed)
                    .custom_formatter(|v, _| fmt_num(v))
                    .custom_parser(|s| s.trim().replace([',', '_', ' '], "").parse::<f64>().ok())
                    .min_decimals(0),
            );
            let active = r.dragged() || r.has_focus();
            if active {
                ui.memory_mut(|m| {
                    m.data.insert_temp(id.with("editing"), true);
                    m.data.insert_temp(id.with("value"), shown);
                });
            }
            let commit = r.drag_stopped() || r.lost_focus() || (r.changed() && !active);
            if commit {
                ui.memory_mut(|m| m.data.insert_temp(id.with("editing"), false));
                let new_si = shown * u.factor + u.offset;
                if (new_si - si).abs() > 1e-12 * si.abs().max(1e-300) {
                    out = Some(new_si);
                }
            }
        } else {
            ui.label(egui::RichText::new(fmt_num(shown)).color(TEXT));
        }
        if us.len() > 1 {
            egui::ComboBox::from_id_salt(id.with("combo")).selected_text(egui::RichText::new(us[unit].label).color(MUTED)).width(96.0).show_ui(ui, |ui| {
                for (i, x) in us.iter().enumerate() {
                    ui.selectable_value(&mut unit, i, x.label);
                }
            });
            ui.memory_mut(|m| m.data.insert_temp(id.with("unit"), unit));
        } else {
            ui.label(egui::RichText::new(us[0].label).color(MUTED));
        }
        if let Some(q) = quality {
            quality_badge(ui, q);
        }
    });
    out
}
