#!/usr/bin/env python3
"""Fetch real Solar System state vectors from NASA/JPL Horizons and cache them as the
dataset embedded in the simulation: crates/cosmogon_sim/data/horizons_sol.toml.

Pipeline: download -> normalise (units, frame) -> validate -> write a versioned cache.
The app never calls Horizons at run time; it ships this cache and works offline. Re-run
this script to refresh the dataset (bump DATASET_VERSION when the content changes). Old
sandboxes keep the data they were created with because initial conditions are copied
into each save.

Source: JPL Horizons API (https://ssd.jpl.nasa.gov/api/horizons.api), planetary and
satellite ephemerides DE441 / JPL satellite solutions. NASA/JPL data are not subject to
copyright in the US; attribution requested: "NASA/JPL Horizons On-Line Ephemeris System".

Frame: ICRF axes rotated to the ecliptic & mean equinox of J2000 (REF_PLANE=ECLIPTIC),
origin at the Solar System barycentre, units km and km/s, TDB time scale.

Usage: python3 tools/fetch_horizons.py [YYYY-MM-DD]
       python3 tools/fetch_horizons.py --validation YYYY-MM-DD
           writes heliocentric reference positions used by the integrator validation test
           (crates/cosmogon_sim/data/horizons_validation_<year>.rs)
"""
import json, math, os, sys, time, urllib.parse, urllib.request

DATASET_VERSION = 1
VALIDATION = len(sys.argv) > 1 and sys.argv[1] == "--validation"
EPOCH = sys.argv[2] if VALIDATION else (sys.argv[1] if len(sys.argv) > 1 else "2026-01-01")

# Cosmogon body name -> Horizons command. Must match the bodies in data/sol.toml.
# Giant planets use their *system barycentres* (5, 6, 7, 8): in Cosmogon their major moons
# ride analytic "rails" and their mass is carried by the planet particle, so the particle
# stands for the barycentre. (The planet centre wobbles ~1–2 m/s around it because of its
# moons — 50 000 km of error per year if mistaken for the barycentre.)
TARGETS = [
    ("Sun", "10"),
    ("Mercury", "199"),
    ("Venus", "299"),
    ("Earth", "399"),
    ("Mars", "499"),
    ("Jupiter", "5"),
    ("Saturn", "6"),
    ("Uranus", "7"),
    ("Neptune", "8"),
    ("Moon", "301"),
    ("Io", "501"),
    ("Europa", "502"),
    ("Ganymede", "503"),
    ("Callisto", "504"),
    ("Titan", "606"),
    ("Enceladus", "602"),
]

API = "https://ssd.jpl.nasa.gov/api/horizons.api"


def fetch(command, center="500@0"):
    params = {
        "format": "json",
        "COMMAND": f"'{command}'",
        "OBJ_DATA": "'NO'",
        "MAKE_EPHEM": "'YES'",
        "EPHEM_TYPE": "'VECTORS'",
        "CENTER": f"'{center}'",
        "START_TIME": f"'{EPOCH}'",
        "STOP_TIME": f"'{EPOCH} 00:01'",
        "STEP_SIZE": "'1'",
        "REF_PLANE": "'ECLIPTIC'",
        "REF_SYSTEM": "'ICRF'",
        "VEC_TABLE": "'2'",
        "OUT_UNITS": "'KM-S'",
        "CSV_FORMAT": "'YES'",
        "TIME_TYPE": "'TDB'",
    }
    url = API + "?" + urllib.parse.urlencode(params, safe="'@")
    with urllib.request.urlopen(url, timeout=60) as r:
        d = json.load(r)
    result = d["result"]
    source = ""
    for line in result.splitlines():
        if line.startswith("Target body name:"):
            source = line.split("{source:")[-1].rstrip("}").strip() if "{source:" in line else "barycentre"
    soe = result.index("$$SOE") + len("$$SOE")
    row = result[soe:result.index("$$EOE")].strip().splitlines()[0]
    f = [x.strip() for x in row.split(",")]
    jd = float(f[0])
    x, y, z, vx, vy, vz = (float(v) for v in f[2:8])
    return jd, (x, y, z), (vx, vy, vz), source, d["signature"]["version"]


def main():
    rows = []
    for name, cmd in TARGETS:
        jd, p, v, source, api_version = fetch(cmd)
        rows.append((name, cmd, jd, p, v, source))
        print(f"{name:10s} {cmd:>4s}  r = {math.sqrt(sum(c*c for c in p)) / 1.495978707e8:9.5f} AU   [{source}]")
        time.sleep(0.4)  # be polite to the public API

    # Validation: one epoch for all rows, plausible heliocentric distances.
    jd0 = rows[0][2]
    assert all(abs(r[2] - jd0) < 1e-9 for r in rows), "rows are not at a single epoch"
    sun = rows[0][3]
    expected_au = {"Mercury": 0.39, "Venus": 0.72, "Earth": 1.0, "Mars": 1.52, "Jupiter": 5.2, "Saturn": 9.5, "Uranus": 19.2, "Neptune": 30.1}
    for name, _, _, p, _, _ in rows:
        if name in expected_au:
            d = math.dist(p, sun) / 1.495978707e8
            assert abs(d / expected_au[name] - 1.0) < 0.25, f"{name} at {d} AU is implausible"

    out = os.path.join(os.path.dirname(__file__), "..", "crates", "cosmogon_sim", "data", "horizons_sol.toml")
    with open(out, "w") as f:
        f.write("# GENERATED by tools/fetch_horizons.py — do not edit by hand.\n")
        f.write("# Barycentric state vectors of the Solar System from NASA/JPL Horizons.\n")
        f.write("# Frame: ecliptic & mean equinox J2000 (ICRF), origin Solar System barycentre.\n")
        f.write("# Units: km, km/s. Time scale: TDB.\n\n")
        f.write("[dataset]\n")
        f.write('provider = "NASA/JPL Solar System Dynamics"\n')
        f.write('name = "JPL Horizons On-Line Ephemeris System"\n')
        f.write(f"version = {DATASET_VERSION}\n")
        f.write(f'api_version = "{api_version}"\n')
        f.write(f'epoch = "{EPOCH} 00:00:00 TDB"\n')
        f.write(f"epoch_jd_tdb = {jd0:.6f}\n")
        f.write(f'retrieved_utc = "{time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}"\n')
        f.write('license = "NASA/JPL data: not subject to US copyright; attribution requested"\n')
        f.write('attribution = "NASA/JPL Horizons On-Line Ephemeris System"\n\n')
        for name, cmd, _, p, v, source in rows:
            f.write("[[body]]\n")
            f.write(f'name = "{name}"\n')
            f.write(f'horizons_id = "{cmd}"\n')
            f.write(f'ephemeris = "{source}"\n')
            f.write(f"position_km = [{p[0]:.9e}, {p[1]:.9e}, {p[2]:.9e}]\n")
            f.write(f"velocity_km_s = [{v[0]:.12e}, {v[1]:.12e}, {v[2]:.12e}]\n\n")
    print(f"wrote {os.path.normpath(out)} ({len(rows)} bodies, epoch JD {jd0} TDB)")


def validation():
    rows = []
    for name, cmd in TARGETS[1:]:
        if name in ("Io", "Europa", "Ganymede", "Callisto", "Titan", "Enceladus"):
            continue
        _, p, _, _, _ = fetch(cmd, center="500@10")
        rows.append((name, p))
        time.sleep(0.4)
    year = EPOCH[:4]
    out = os.path.join(os.path.dirname(__file__), "..", "crates", "cosmogon_sim", "data", f"horizons_validation_{year}.rs")
    with open(out, "w") as f:
        f.write(f"// GENERATED by tools/fetch_horizons.py --validation {EPOCH} — heliocentric positions (km),\n")
        f.write("// ecliptic J2000, from NASA/JPL Horizons. Reference values for the integrator test.\n")
        f.write(f"pub const HELIO_{year}: &[(&str, [f64; 3])] = &[\n")
        for name, p in rows:
            f.write(f'    ("{name}", [{p[0]:.10e}, {p[1]:.10e}, {p[2]:.10e}]),\n')
        f.write("];\n")
    print("wrote", os.path.normpath(out))


if __name__ == "__main__":
    validation() if VALIDATION else main()
